# Generated by Django 3.1.7 on 2022-12-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='chatid',
            field=models.CharField(default='', max_length=100),
        ),
    ]
