# Generated by Django 3.1.7 on 2022-12-14 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=200)),
                ('entryPrice', models.FloatField()),
                ('markPrice', models.FloatField()),
                ('pnl', models.FloatField()),
                ('roe', models.FloatField()),
                ('time', models.DateTimeField()),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.trader')),
            ],
        ),
    ]
